import { motion } from "framer-motion";
import { FileText, ListChecks, Zap, CheckCircle2 } from "lucide-react";
import { Hero } from "@/components/ui/animated-hero";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";

export default function LandingPage() {
  const features = [
    {
      title: "Resume Parsing",
      description: "Our system extracts your tech stack, programming languages, and experience levels from your uploaded PDF resume automatically.",
      icon: <FileText className="w-8 h-8 text-indigo-400" />,
    },
    {
      title: "Tailored Questions",
      description: "Get custom-built, professional mock interview questions generated on-the-fly specifically targeting your parsed skill badges.",
      icon: <ListChecks className="w-8 h-8 text-indigo-400" />,
    },
    {
      title: "Instant AI Feedback",
      description: "Receive detailed, question-by-question scoring and summary feedback generated by AI. Know exactly where you shine and how to improve.",
      icon: <Zap className="w-8 h-8 text-indigo-400" />,
    },
  ];

  const containerVariants = {
    hidden: {},
    show: {
      transition: {
        staggerChildren: 0.1,
      },
    },
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 20 },
    show: { opacity: 1, y: 0, transition: { type: "spring", stiffness: 100 } },
  };

  return (
    <div className="min-h-screen bg-bgPrimary text-textPrimary overflow-hidden">
      {/* Hero Section */}
      <Hero />

      {/* Features Section */}
      <div className="max-w-6xl mx-auto px-6 pb-32">
        <motion.div
          className="text-center mb-16"
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
        >
          <h2 className="text-3xl md:text-5xl font-bold mb-4">How PrepWise Works</h2>
          <p className="text-slate-400 max-w-xl mx-auto">
            A comprehensive pipeline designed to simulate a real, high-level technical screening.
          </p>
        </motion.div>

        <motion.div
          className="grid md:grid-cols-3 gap-8"
          variants={containerVariants}
          initial="hidden"
          whileInView="show"
          viewport={{ once: true }}
        >
          {features.map((feature, index) => (
            <motion.div key={index} variants={itemVariants}>
              <Card className="h-full border border-slate-800 bg-slate-950/40 hover:border-indigo-500/50 hover:shadow-indigo-500/10 transition-all duration-300 group">
                <CardHeader>
                  <div className="mb-4 p-3 rounded-lg bg-slate-900/50 w-fit group-hover:bg-indigo-950/30 transition-colors">
                    {feature.icon}
                  </div>
                  <CardTitle className="text-xl font-bold text-white group-hover:text-indigo-400 transition-colors">
                    {feature.title}
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <CardDescription className="text-slate-400 text-sm leading-relaxed">
                    {feature.description}
                  </CardDescription>
                </CardContent>
              </Card>
            </motion.div>
          ))}
        </motion.div>
      </div>

      {/* Footer */}
      <footer className="border-t border-slate-800/80 py-8 bg-slate-950/20">
        <div className="max-w-6xl mx-auto px-6 flex flex-col md:flex-row justify-between items-center gap-4">
          <div className="flex items-center gap-2">
            <span className="font-bold text-lg text-white">Prep<span className="text-indigo-400">Wise</span></span>
          </div>
          <p className="text-slate-500 text-xs">
            © {new Date().getFullYear()} PrepWise AI. All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  );
}
